IMAGE_NAME: dotfiles

version: 2
jobs:
  build:
    context: DOCKER_HUB
    working_directory: /${IMAGE_NAME}
    docker:
      - image: docker:17.12.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.1-r1
            pip install \
              --upgrade pip
            pip install \
              docker-compose==1.12.1 \
              awscli==1.14.66
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/${IMAGE_NAME}.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/${IMAGE_NAME}.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=${IMAGE_NAME} -t ${IMAGE_NAME} .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/${IMAGE_NAME}.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/${IMAGE_NAME}.tar
      - run:
          name: Run tests
          command: |
            docker-compose -f ./docker-compose.test.yml up
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker tag ${IMAGE_NAME} "${DOCKER_USER}/${IMAGE_NAME}:${CIRCLE_SHA1}"
              docker push "${DOCKER_USER}/${IMAGE_NAME}:${CIRCLE_SHA1}"
            fi
