IMAGE_NAME: dotfiles

version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-git

    steps:
      - checkout

      - run: bash scripts/generate.sh > Dockerfile

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: docker build -t $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG .

      - run: docker push $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG && sleep 10

      - store_artifacts:
          path: Dockerfile

  test_image:
    docker:
      - image: $DOCKER_USER/dotfiles:16.04
        environment:
          <<: *image_config

    steps:
      - checkout

      - run:
          name: start Xvfb for phantomjs test
          # # command: Xvfb :99
          # # background: true

      - run:
          name: bats tests
          command: |
            mkdir -p test_results/bats
            bats scripts/tests.bats | \
            perl scripts/tap-to-junit.sh > \
            test_results/bats/results.xml
      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results

workflows:
  version: 2
  dockerfile_wizard:
    jobs:
      - build_images:
          context: DOCKER_HUB

      - test_images:
          context: DOCKER_HUB
          requires:
            - build

      - deploy_images:
          context: DOCKER_HUB
          requires:
            - build

workflows:
  version: 2
  dotfiles:
    jobs:
      - build:
          context: DOCKER_HUB

      - test:
          context: DOCKER_HUB
          requires:
            - build

      - deploy:
          context: DOCKER_HUB
          requires:
            - build
